name: Build executables and create release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout Winnow source code
        uses: actions/checkout@v2
        with:
          repository: sul-cidr/ohtap-winnow
          ref: cidr-2021
          path: winnow

      - name: Build Winnow UI application (React)
        run: |
          cd $GITHUB_WORKSPACE/winnow
          npm install
          npm run build

      - name: Copy Winnow assets
        run: |
          cp -av $GITHUB_WORKSPACE/winnow/build $GITHUB_WORKSPACE/main/winnow/www-data
          cp $GITHUB_WORKSPACE/winnow/src/tool_script.py $GITHUB_WORKSPACE/main/winnow/

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get Python Version
        id: get-python-version
        shell: bash
        run: |
          echo "::set-output name=python-version::$(python -c "import sys; print(sys.hexversion)")"

      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: |
            ~/.cache/pip
            src/.venv
          key: ${{ runner.os }}-${{ steps.get-python-version.outputs.python-version }}-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/main
          sudo pip install pipenv
          PIPENV_VENV_IN_PROJECT=1 pipenv sync --dev

      - name: Build Linux executable
        run: |
          cd $GITHUB_WORKSPACE/main
          pipenv run pyinstaller cli.py --hidden-import winnow.tool_script --onefile --name winnow --add-data winnow:winnow
