name: Build executables and create release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Get Python Version
        id: get-python-version
        run: |
          echo "::set-output name=python-version::$(python -c "import sys; print(sys.hexversion)")"
        shell: bash
      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: |
            ~/.cache/pip
            src/.venv
          key: ${{ runner.os }}-${{ steps.get-python-version.outputs.python-version }}-${{ hashFiles('Pipfile.lock') }}
      - name: Install dependencies
        run: |
          sudo pip install pipenv
          PIPENV_VENV_IN_PROJECT=1 pipenv sync --dev
      - name: Build Linux executable
        run: |
          pipenv run pyinstaller cli.py --hidden-import winnow.tool_script --onefile --name winnow --add-data winnow:winnow
